server:
  port: 8082
spring:
  h2:
    console:
      enabled: true
  application:
    name: COURSE-SERVICE


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost