#https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html
zuul:
  ignoredServices: '*'
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  #Service will be mapped under the /api URI
  prefix: /v1/api
  routes:
    STUDENT-SERVICE:
      path: /student-service/**
      serviceId: STUDENT-SERVICE
    COURSE-SERVICE:
      path: /course-service/**
      serviceId: COURSE-SERVICE
    PAYMENT-SERVICE:
       path: /payment-service/**
       serviceId: PAYMENT-SERVICE


server:
  port: 8083

spring:
  application:
    name: STUDENT-COURSE-GATWAY

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000