spring:
  application:
    name: STUDENT-COURSE-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smishra1000/student-course-config-server

server:
  port: 8085

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost