server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  application:
    name: STUDENT-SERVICE
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
