spring:
  application:
    name: STUDENT-COURSE-GATEWAY-SERVICE
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - POST
      routes:
        - id: course-service
          uri : lb://COURSE-SERVICE
          predicates:
            - Path=/course/**
          filters:
            - name: CircuitBreaker
              args:
                name: course-service
                fallbackuri: forward:/courseFallBack
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
          filters:
            - name: CircuitBreaker
              args:
                name: student-service
                fallbackuri: forward:/studentFallBack

server:
    port: 8084

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000