spring:
  application:
    name: STUDENT-COURSE-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: course-service
          uri : lb://COURSE-SERVICE
          predicates:
            - Path=/course/**
          filters:
            - name: CircuitBreaker
              args:
                name: course-service
                fallbackuri: forward:/courseFallBack
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
          filters:
            - name: CircuitBreaker
              args:
                name: student-service
                fallbackuri: forward:/studentFallBack


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
    port: 8084

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000